name: Auto-update Department Field

on:
  issues:
    types: [opened, edited]

jobs:
  update-department-field:
    runs-on: ubuntu-latest
    steps:
      - name: Update Department Field based on issue label
        uses: octokit/request-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          route: PATCH /projects/columns/cards/{card_id}
          card_id: ${{ github.event.issue.id }}
          content: |
            {
              "field": "department",
              "value": "PM"
            }
